USE campamento_verano;

CREATE TABLE IF NOT EXISTS crm_notas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_registro VARCHAR(255) NOT NULL,
  nota MEDIUMTEXT NOT NULL,
  created_by VARCHAR(100) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  INDEX (id_registro),
  INDEX (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
