CREATE TABLE IF NOT EXISTS crm_estados_inscripciones (
  id INT AUTO_INCREMENT PRIMARY KEY,
  id_registro VARCHAR(255) NOT NULL UNIQUE,
  estado VARCHAR(50) NOT NULL,
  color  VARCHAR(20) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
